# Generated by Django 2.2.7 on 2019-11-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
