# Generated by Django 2.2.7 on 2019-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0003_home_fourth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_one', models.CharField(blank=True, max_length=30)),
                ('title_one_sub1', models.CharField(blank=True, max_length=30)),
                ('title_one_sub2', models.CharField(blank=True, max_length=30)),
                ('title_two', models.TextField(blank=True, max_length=520)),
            ],
        ),
    ]
