# Generated by Django 2.2.7 on 2019-11-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0004_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
