# Generated by Django 2.2.7 on 2019-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0005_hero_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_one', models.CharField(blank=True, max_length=30)),
                ('t_one_sub1', models.CharField(blank=True, max_length=30)),
                ('t_one_sub2', models.CharField(blank=True, max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('t_two', models.TextField(blank=True, max_length=520)),
                ('t_two_sub1', models.CharField(blank=True, max_length=30)),
                ('t_two_sub2', models.CharField(blank=True, max_length=30)),
                ('t_three', models.TextField(blank=True, max_length=520)),
                ('t_three_sub1', models.CharField(blank=True, max_length=30)),
                ('t_three_sub2', models.CharField(blank=True, max_length=30)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
