# Generated by Django 2.2.7 on 2019-11-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0006_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abt',
        ),
    ]
