# Generated by Django 2.2.7 on 2019-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0007_auto_20191128_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='abt',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='abt',
            name='t_two_sub2',
            field=models.TextField(blank=True, max_length=520),
        ),
    ]
