# Generated by Django 2.2.7 on 2019-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0008_auto_20191128_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abt',
            name='t_three_sub2',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
