# Generated by Django 2.2.7 on 2019-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0009_auto_20191128_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='abt',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='abt',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='abt',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='abt',
            name='quality1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='abt',
            name='quality2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='abt',
            name='quality3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
