# Generated by Django 2.2.7 on 2019-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0010_auto_20191128_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(blank=True, max_length=6)),
                ('d1', models.TextField(blank=True, max_length=18)),
                ('p1', models.TextField(blank=True, max_length=520, null=True)),
                ('p1_d', models.TextField(blank=True, max_length=520, null=True)),
                ('p2', models.TextField(blank=True, max_length=520, null=True)),
                ('p2_d', models.TextField(blank=True, max_length=520, null=True)),
                ('p3', models.TextField(blank=True, max_length=520, null=True)),
                ('p3_d', models.TextField(blank=True, max_length=520, null=True)),
                ('p4', models.TextField(blank=True, max_length=520, null=True)),
                ('p4_d', models.TextField(blank=True, max_length=520, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
