# Generated by Django 2.2.7 on 2019-11-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0013_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
