# Generated by Django 2.2.7 on 2019-12-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0014_team_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
