# Generated by Django 2.2.7 on 2019-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0016_works_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, max_length=520, null=True)),
                ('details', models.TextField(blank=True, max_length=520, null=True)),
                ('review1', models.TextField(blank=True, max_length=520, null=True)),
                ('review2', models.TextField(blank=True, max_length=520, null=True)),
                ('review3', models.TextField(blank=True, max_length=520, null=True)),
                ('review4', models.TextField(blank=True, max_length=520, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
