# Generated by Django 2.2.7 on 2019-12-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0019_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField(blank=True, max_length=520, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
