# Generated by Django 2.2.7 on 2019-12-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0022_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
