# Generated by Django 2.2.7 on 2019-12-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inaraApp', '0025_post_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
    ]
